### ISSUE TITLE
Please explain this action in the readme? 

### ISSUE THREAD

**Issue by geoidesic** [tfadeyi/start-voting#1]
What does it do?
Are there dependencies?
How to use it?

**Comment by tfadeyi** [comment]
Hi @geoidesic currently this project and action are under development during my spare time. It's not meant for real usage.

> What does it do?

It's a github action to run votes inside of github issues, similar to https://github.com/tfadeyi/oss-governance-test/issues/41.
Any issues opened with a specific label, that you can set, will have a voting comment.

> Are there dependencies?

It requires a github token, since it uses the github api. It doesn't require any other dependency as it runs on as a github action.

>  How to use it?

I would suggest not using it for now has it's still not ready.


Would this type of github action be something you would be interested in?

**Comment by geoidesic** [comment]
Not knowing much about it, it's hard to say. I have been looking for a feature voting thing in GitHub. Yours is the closest that popped up on search. Considered writing my own but it's a bridge far too far. It seems like a big, missing, no brainer for open source dev.

**Comment by tfadeyi** [comment]
I'm planning to continue the work on this. But there are a couple other projects available like https://github.com/cncf/gitvote that do something similar

**Comment by geoidesic** [comment]
Ok tx.
